excluded: # 执行 linting 时忽略的路径。 优先级比 `included` 更高。
  - Pods
  - SwiftDemo/Vender

file_length: 1000 #文件的行数

# 这段代码设置了 line_length 的检查规则：
line_length:
  warning: 1000 # warning: 110 表示单行字符数超过 110 时抛出警告，你也可以设置为其他的值。
  ignores_function_declarations: true #ignores_function_declarations 表示是否忽略检查函数定义的长度
  ignores_comments: true #ignores_comments 设置是否忽略检查注释的长度
